// prebuild.js
require('dotenv').config();

console.log('\n📦 Environment variables check:');
console.log('---------------------------------------');
console.log('CLERK_KEY:', process.env.EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY ? 
  `FOUND (starts with ${process.env.EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY.substring(0, 5)}...)` : 
  'MISSING ⚠️');
console.log('API_IP:', process.env.EXPO_PUBLIC_API_IP ? 
  `FOUND (${process.env.EXPO_PUBLIC_API_IP})` : 
  'MISSING ⚠️');
console.log('---------------------------------------');

// Enhanced check to verify the exact issue
if (!process.env.EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY || !process.env.EXPO_PUBLIC_API_IP) {
  console.log('\n⚠️ Some environment variables are missing!');
  console.log('Please check your .env file has the following format:');
  console.log('---------------------------------------');
  console.log('EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_your_key_here');
  console.log('EXPO_PUBLIC_API_IP=your_ip_here');
  console.log('---------------------------------------');
  console.log('Make sure there are no spaces, quotes, or comments in these lines.');
  console.log('The .env file should be in the root of your project.\n');
}

// Instead of modifying app.config.js, create a temporary environment variables file
const fs = require('fs');
const path = require('path');

const envJsPath = path.join(__dirname, 'env.js');

// Create an env.js file that exports the environment variables
const envJsContent = `// Generated by prebuild.js - do not edit directly
// This file exports environment variables for use in app.config.js

module.exports = {
  CLERK_KEY: "${process.env.EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY || ''}",
  API_URL: "${process.env.EXPO_PUBLIC_API_IP || ''}",
};
`;

// Write the env.js file
fs.writeFileSync(envJsPath, envJsContent);

console.log('✅ Environment variables saved to env.js');
console.log('🚀 Environment check complete. Ready for prebuild.\n');
